import {
  Sparkles as LucideSparkles,
  Landmark,
  Castle,
  Building2,
  CheckCircle2,
  Flame,
} from 'lucide-react';

export {
  FaArrowLeft as ArrowLeft,
  FaArrowRight as ArrowRight,
  FaArrowUpRightFromSquare as ArrowUpRight,
  FaArrowUpRightFromSquare as ExternalLink,
  FaArrowTrendUp as TrendingUp,
  FaAudioDescription as AudioDescription,
  FaBell as Bell,
  FaBookOpen as BookOpen,
  FaBrain as Brain,
  FaBullhorn as Target,
  FaCalendarDays as Calendar,
  FaChartSimple as Activity,
  FaChartSimple as BarChart3,
  FaCheck as Check,
  FaCircleCheck as CheckCircle,
  FaCircleInfo as AlertCircle,
  FaCircleInfo as Info,
  FaCircleQuestion as HelpCircle,
  FaClock as Clock,
  FaClock as Clock3,
  FaCompass as Compass,
  FaCrown as Crown,
  FaEarthAsia as Globe,
  FaEnvelope as Mail,
  FaGraduationCap as GraduationCap,
  FaHouse as Home,
  FaLightbulb as Lightbulb,
  FaLock as Lock,
  FaMap as Map,
  FaMapPin as MapPin,
  FaMedal as Medal,
  FaMessage as MessageCircle,
  FaMessage as MessageCircleMore,
  FaMessage as MessageSquare,
  FaMessage as MessageSquareMore,
  FaMicrophone as Mic,
  FaMusic as Music,
  FaPaperPlane as Send,
  FaPenNib as PenTool,
  FaPen as Edit,
  FaPlay as Play,
  FaPlus as Plus,
  FaCirclePlus as PlusCircle,
  FaRightFromBracket as LogOut,
  FaRotateRight as RefreshCw,
  FaRocket as Rocket,
  FaMagnifyingGlass as Search,
  FaShieldHalved as Shield,
  FaShield as ShieldCheck,
  FaStar as Star,
  FaTriangleExclamation as AlertTriangle,
  FaTrophy as Award,
  FaTrophy as Trophy,
  FaTrash as Trash2,
  FaUsers as Users,
  FaUser as User,
  FaUserPlus as UserPlus,
  FaUserCheck as UserCheck,
  FaUserSecret as UserSearch,
  FaVolumeHigh as AudioLines,
  FaVolumeHigh as Headphones,
  FaVolumeHigh as Volume2,
  FaXmark as X,
  FaCircleXmark as XCircle,
  FaBolt as Zap,
  FaClipboard as Layout,
  FaClipboard as LayoutDashboard,
  FaGear as Settings,
  FaFlag as Flag,
  FaShieldHalved as ShieldAlert,
  FaChevronRight as ChevronRight,
  FaChevronLeft as ChevronLeft,
  FaChevronDown as ChevronDown,
  FaChevronUp as ChevronUp,
  FaEllipsisVertical as MoreVertical,
  FaEllipsis as MoreHorizontal,
  FaDownload as Download,
  FaRobot as Bot,
  FaRotateLeft as History,
  FaRotateLeft as RotateCcw,
  FaFilter as Filter,
  FaEye as Eye,
  FaEyeSlash as EyeOff,
  FaShareNodes as Share,
  FaFileLines as FileText,
  FaFolder as Folder,
  FaMoon as Moon,
  FaSun as Sun,
  FaFloppyDisk as Save,
  FaComputerMouse as Mouse,
} from 'react-icons/fa6';

export {
  LucideSparkles as Sparkles,
  Landmark,
  Castle,
  Building2,
  CheckCircle2,
  Flame,
};
